sprint_8-solution-time-and-duration
iwfua/java-kanban pull request #3
Opened 2024-04-25 18:57 UTC by iwfua

2024-04-26 15:47 UTC, YazykovMikhail requested changes

2024-04-26 15:47 UTC, YazykovMikhail commented on src/ru/yandex/javacource/zuborev/schedule/manager/InMemoryTaskManager.java
> +    protected TreeSet<Task> prioritizedTasks;
Отлично

2024-04-26 15:47 UTC, YazykovMikhail commented on src/ru/yandex/javacource/zuborev/schedule/manager/InMemoryTaskManager.java
> +    public Optional<Task> findIntersection(Task task) {
Пусть метод тогда возвращает true/false 
Все такие  Optional используется что бы не ловить NPE, а не что бы по нему проверять условия

2024-04-26 15:47 UTC, YazykovMikhail commented on src/ru/yandex/javacource/zuborev/schedule/manager/InMemoryTaskManager.java
Стоит сделать метод по вычислению времени окончания Эпика
```

protected void updateEpic(int epicId) {
		Epic epic = epics.get(epicId);
		updateEpicStatus(epic);
		updateEpicDuration(epic);
	}

	private void updateEpicDuration(Epic epic) {
		List<Integer> subs = epic.getSubtaskIds();
		if (subs.isEmpty()) {
			epic.setDuration(0L);
			return;
		}
		LocalDateTime start = LocalDateTime.MAX;
		LocalDateTime end = LocalDateTime.MIN;
		long duration = 0L;
		for (int id : subs) {
			final Subtask subtask = subtasks.get(id);
			final LocalDateTime startTime = subtask.getStartTime();
			final LocalDateTime endTime = subtask.getEndTime();
			if (startTime.isBefore(start)) {
				start = startTime;
			}
			if (endTime.isAfter(end)) {
				end = endTime;
			}
			duration += subtask.getDuration();
		}
		epic.setDuration(duration);
		epic.setStartTime(start);
		epic.setEndTime(end);
	}
```

и метод updateEpic вызывать везде, где раньше вызывался updateStatus, ведь время окончания эпика тоже зависит от сабтасок,  и теперь проверки будут вызываться вместе

2024-04-26 15:47 UTC, YazykovMikhail commented on src/ru/yandex/javacource/zuborev/schedule/manager/InMemoryTaskManager.java
> +        }
если свободного времени нет, стоит выбрасывать сиключение, ведь задачу нельзя добавить, раз промежутка нет

2024-04-26 15:47 UTC, YazykovMikhail commented on src/ru/yandex/javacource/zuborev/schedule/manager/InMemoryTaskManager.java
> +    public Optional<Task> findIntersection(Task task) {
А еще лучше будет сделать метод который будет сам добавлять, а если добавить нельзя выбрасывать исключение:

	```
private void prioritize(Task task) {
		final LocalDateTime startTime = task.getStartTime();
		final LocalDateTime endTime = task.getEndTime();
		for (Task t : prioritizedTasks) {
			final LocalDateTime existStart = t.getStartTime();
			final LocalDateTime existEnd = t.getEndTime();
			if (!endTime.isAfter(existStart)) {// newTimeEnd <= existTimeStart
				continue;
			}
			if (!existEnd.isAfter(startTime)) {// existTimeEnd <= newTimeStart
				continue;
			}

			throw new TaskValidationException("Задача пересекаются с id=" + t.getId() + " c " + existStart + " по " + existEnd);
		}

		prioritizedTasks.add(task);
	}
```

2024-04-26 15:47 UTC, YazykovMikhail commented on test/ru/yandex/javacource/zuborev/schedule/InMemoryHistoryManagerTests.java
>  package ru.yandex.javacource.zuborev.schedule;
ru.yandex.javacource.zuborev.schedule.manager;
добавь пакет и физичкую папку, ты же тетсируешь Классы которые находятся в папке manager

2024-04-28 11:41 UTC, iwfua commented on src/ru/yandex/javacource/zuborev/schedule/manager/InMemoryTaskManager.java
> +    public Optional<Task> findIntersection(Task task) {
Подправил по вашему примеру
Так же добавил отлов ManagerSaveException

2024-04-28 11:41 UTC, iwfua commented on src/ru/yandex/javacource/zuborev/schedule/manager/InMemoryTaskManager.java
Понял, подправил по вашему примеру

2024-04-28 11:41 UTC, iwfua commented on src/ru/yandex/javacource/zuborev/schedule/manager/InMemoryTaskManager.java
> +        }
Добавил отлов исключения, которое кидает метод ```prioritize()``` при проверке на пересечения

2024-04-28 11:41 UTC, iwfua commented on test/ru/yandex/javacource/zuborev/schedule/InMemoryHistoryManagerTests.java
>  package ru.yandex.javacource.zuborev.schedule;
Понял, подправил

2024-04-28 19:41 UTC, YazykovMikhail requested changes

2024-04-28 19:41 UTC, YazykovMikhail commented on src/ru/yandex/javacource/zuborev/schedule/manager/InMemoryTaskManager.java
> +        } catch (ManagerSaveException | NullPointerException e) {
вот как раз олавливать не нужно, в этом и смысл выбрасывать исключпение, что все ошибка, дальше выполнение невозможно
И в исключени описывается почему, и фронт который будет вызыать эти методы сможет понять что случилось

2024-04-28 19:41 UTC, YazykovMikhail commented on src/ru/yandex/javacource/zuborev/schedule/manager/InMemoryTaskManager.java
> +        }
вот как раз олавливать не нужно, в этом и смысл выбрасывать исключпение, что все ошибка, дальше выполнение невозможно
И в исключени описывается почему, и фронт который будет вызыать эти методы сможет понять что случилось

2024-04-28 19:41 UTC, YazykovMikhail commented on src/ru/yandex/javacource/zuborev/schedule/manager/InMemoryTaskManager.java
> +    public Optional<Task> findIntersection(Task task) {
вот как раз олавливать не нужно, в этом и смысл выбрасывать исключпение, что все ошибка, дальше выполнение невозможно
И в исключени описывается почему, и фронт который будет вызыать эти методы сможет понять что случилось

Это сейчас приложении закрывается, потом когда будет приложении работать на сервере, оно продолжит работать дальше

2024-04-30 13:52 UTC, YazykovMikhail approved these changes

2024-05-01 08:06 UTC, merged